### ISSUE TITLE
weird screen

### ISSUE THREAD

**Issue by efschu** [telescope-proj/lgproxy#2]
Hi,

I try to setup this. Installed lg on Win11 VM, running on proxmox 7.1, built lgproxy on proxmox and built lgproxy on mint21 (client)

It does work partial, but it displays some strage colors all time. I dunno where to start to debug, it could be related to lg, lgproxy, or something else:
![Bildschirmfoto vom 2022-08-08 14-16-55](https://user-images.githubusercontent.com/51944948/183425140-eb24a478-ad08-483b-a080-cbba27b0a422.png)

**Comment by beanfacts** [comment]
Hi,
Thanks for checking out LGProxy.

Could you please provide the following information?
- Can you describe your setup in more detail? At a minimum we would like to know:
  - The Libfabric versions on both sides -> `fi_info --version`
  - GPU models on both sides and capture method used in LG
  - The models of network adapters you are using
- Does this issue persist on more common resolutions such as 1280x720 or 1920x1080?
- Is there any motion on the screen? A known bug with lgproxy is strange looking output (or commonly *no output*) when nothing has updated on screen: https://telescope-proj.github.io/lgproxy/bugs/knownbugs.html, try playing a video and see if the issue is reproduced
  - In line with the above point, use the Looking Glass profiler (ScrLk + T) to observe if any updates are being sent when the video is playing.
 
- If after motion there are still issues, please set the log level to debug for both LibTRF and LGProxy, on both sides, and attach the file(s) in a reply. See the following on how to do so: https://telescope-proj.github.io/lgproxy/user/running.html#setting-the-log-level

**Comment by efschu** [comment]
client/host:
fi_info: 1.11.0
libfabric: 1.11.0
libfabric api: 1.11

RX Vega64 on Windows
iGPU from Ryzen 5700G on client side
Mellanox ConnectX-4LX on host/client

issue persist on lower resolutions

there is motion on screen and the weird colors are updated when picture on windows host is changing


[I]    996366423               app.c:356  | captureStop                    | ==== [ Capture Stop ] ====
[I]    996386756               app.c:842  | app_main                       | Host application exited
[I]    996843629              time.c:85   | windowsSetTimerResolution      | System timer resolution: 500.0 Î¼s
[I]    996844107               app.c:544  | app_main                       | Looking Glass Host (B5.0.1)
[I]    996844552           cpuinfo.c:36   | lgDebugCPU                     | CPU Model: AMD Eng Sample: ZS1711E3VIVG5_24/17_N
[I]    996845044           cpuinfo.c:37   | lgDebugCPU                     | CPU: 64 cores, 32 threads
[I]    996846986           ivshmem.c:131  | ivshmemInit                    | IVSHMEM 0* on bus 0x0, device 0x1, function 0x0
[I]    996855015               app.c:561  | app_main                       | IVSHMEM Size     : 128 MiB
[I]    996855340               app.c:562  | app_main                       | IVSHMEM Address  : 0x2F20000
[I]    996855652               app.c:563  | app_main                       | Max Pointer Size : 1024 KiB
[I]    996856044               app.c:564  | app_main                       | KVMFR Version    : 14
[I]    996856585               app.c:625  | app_main                       | Max Frame Size   : 62 MiB
[I]    996856928               app.c:650  | app_main                       | Trying           : DXGI
[I]    996860992              dxgi.c:322  | dxgi_init                      | Device Name       : \\.\DISPLAY1
[I]    996861338              dxgi.c:323  | dxgi_init                      | Device Description: Radeon RX Vega
[I]    996861670              dxgi.c:324  | dxgi_init                      | Device Vendor ID  : 0x1002
[I]    996862001              dxgi.c:325  | dxgi_init                      | Device Device ID  : 0x687f
[I]    996862339              dxgi.c:326  | dxgi_init                      | Device Video Mem  : 8120 MiB
[I]    996862718              dxgi.c:327  | dxgi_init                      | Device Sys Mem    : 0 MiB
[I]    996863066              dxgi.c:328  | dxgi_init                      | Shared Sys Mem    : 16380 MiB
[I]    996894709              dxgi.c:435  | dxgi_init                      | Feature Level     : 0xc100
[I]    996895077              dxgi.c:436  | dxgi_init                      | Capture Size      : 1280 x 720
[I]    996895479              dxgi.c:437  | dxgi_init                      | AcquireLock       : enabled
[I]    996897644              dxgi.c:527  | dxgi_init                      | Source Format     : DXGI_FORMAT_B8G8R8A8_UNORM
[I]    996898376               app.c:675  | app_main                       | Using            : DXGI
[I]    996898749               app.c:676  | app_main                       | Capture Method   : Asynchronous
[I]   1054786724               app.c:350  | captureStart                   | ==== [ Capture Start ] ====
[I]   1054787473               app.c:290  | frameThread                    | Frame thread started

**Comment by beanfacts** [comment]
It looks as if you are using the older release build of Looking Glass with LGProxy, which has a different data format to the texture-compression-enabled version.

The texture-compression enabled version has a commit hash of `19f30ae`.
`16:38:59 INFO lp_sink.c:167: Looking Glass Build: B5-347-g719f30ae`

The host is running B5.0.1.
`[I] 996844107 app.c:544 | app_main | Looking Glass Host (B5.0.1)`

Additionally, your client is running commit `d376dc4`.

You'll have to use the same version when compiling LGProxy as well as running the host and client. By default LGProxy uses the Telescope-patched version of Looking Glass. Try using this version- the build steps are similar to upstream Looking Glass.

Client:
```
git clone https://github.com/telescope-proj/LookingGlass --recursive -b client-dxtc
cd LookingGlass
mkdir client/build
cd client/build
cmake ../
make -j $(nproc)
```

Host (cross compile method):
```
git clone https://github.com/telescope-proj/LookingGlass --recursive -b client-dxtc
cd LookingGlass
mkdir host/build
cd host/build
cmake -DCMAKE_TOOLCHAIN_FILE=../toolchain-mingw64.cmake ..
make -j $(nproc)
```

**Comment by efschu** [comment]
Yes, thanks, it was the version mismatch. It is working now.

Two more questions, where can I define polling interval and where can I set which texture compression it is using?

**Comment by beanfacts** [comment]
The polling interval in milliseconds can be controlled with the `-r` flag in the LGProxy client and host. It can be set to any positive value between 0 and the timeout duration, but the zero option will pin the CPU usage at 200% (2 cores). We didn't observe any significant benefit when setting this to 0.

For example: `./sink -h 10.0.0.10 -p 12345 -r 1`

Format conversion can be controlled using the `app:transcode` option, either in the Looking Glass config:

```
[app]
transcode=format
```

or on the command line as follows (MSYS2 Shell):
```
./looking-glass-host.exe app:transcode=format
```

Where `format` can be `dxt1`, `dxt5`, `etc2`, `etc2eac`, or `rgb`. The following conversions are supported based on your source format:
| Input Format | Output Formats                                                                    |
|--------------|-----------------------------------------------------------------------------------|
| BGRA         | **RGBA** [1], **RGB**, **DXT1** [2], **DXT5** [2], **ETC2** [3], **ETC2 EAC** [3] |
| RGBA         | **BGRA** [1], **RGB**, **DXT1**, **DXT5**, **ETC2** [2][3], **ETC2 EAC** [2][3]   |
| RGBA10       | N/A                                                                               |
| RGBA16F      | N/A                                                                               |

[1] Supported by Telescope LibTTC, but not LGProxy
[2] Uses intermediate conversions, performance may be lower
[3] Proof of concept, poor performance especially on older / lower clocked machines

Compared to BGRA or RGBA:
- `RGB` reduces bandwidth by a ratio of 4:3 (-25%) with no quality loss.
- `DXT5` and `ETC2 EAC` reduce bandwidth by a ratio of 4:1 (-75%) with noticeable quality loss
- `DXT1` and `ETC2` reduce bandwidth by a ratio of 8:1 (-87%) with the same quality loss as above

It should be noted that unfortunately many AMD GPUs unpack RGB to BGRA before GPU upload, which can increase latency (around 1-2 frames in our testing). You can experiment with the options to see which compromise of quality/latency is acceptable to you.

**Comment by efschu** [comment]
Tnx again, cant "see" any latency difference between plain, rgb, dxt5 or dxt1. Guess this is because I have enough bandwidth. (And maybe because I'm "old")

How to force lgproxy to use tcp/udp ip instead of rdma, for testing purpose? (Guess it is using rdma automaticaly if connection is capable?)

**Comment by beanfacts** [comment]
> Tnx again, cant "see" any latency difference between plain, rgb, dxt5 or dxt1.

Yep, the benefit of doing minimal encoding :) In many cases you have to put a camera up to the screens on both sides to notice the latency (which can be effectively zero due to how fast the Looking Glass capture is + how lean the Linux render pipeline is compared to Windows).

![telescope-sample-issue-2](https://user-images.githubusercontent.com/43068204/183651928-7abebd73-8d55-4f7a-9c72-635e6a4bd97e.png)

> How to force lgproxy to use tcp/udp ip instead of rdma, for testing purpose?

It should be possible to limit the providers using Libfabric's `FI_PROVIDER` environment variable containing the transports you want to limit Libfabric to, for example:
`FI_PROVIDER=verbs,tcp ./sink -h 10.0.0.10 -p 12345`

You can do this on either side, and it should negotiate down to the interfaces you selected. I never tested this though so not sure if it works. You can check the providers available for your specific version in the Libfabric [manual](https://ofiwg.github.io/libfabric/v1.11.0/man/fi_provider.7.html), but here's a shortlist:
- `verbs`: RDMA Verbs API (InfiniBand, RoCE, iWARP adapters)
- `tcp`: TCP
- `udp`: UDP

We have only validated TCP and RDMA Verbs functionality, however.

> Guess it is using rdma automaticaly if connection is capable?

Usually yes, it uses what Libfabric thinks is the best transport (usually RDMA over Verbs or a similar transport like PSM), falling back to TCP if hardware acceleration is unavailable or incorrectly configured. You can check in your LGProxy logs to see which transport ended up being used:

`16:38:59 INFO trfi_ncp_client.c:539: Candidate transport verbs;ofi_rxm @ trfx_sockaddr_in://192.168.40.11:48661`

**Comment by beanfacts** [comment]
As the problem is solved I will be closing this issue, but if you have any further questions feel free to open a discussion.
