### ISSUE TITLE
LG Version hardcoded

### ISSUE THREAD

**Issue by efschu** [telescope-proj/lgproxy#3]
Hi,

I want to use the "standard" build from lg which provides nvfbc support and I dont need the texture compression, but when I start it i get this:

`[E]   1253393979              main.c:840  | reportBadVersion               | The host application is not compatible with this client
[E]   1253393982              main.c:841  | reportBadVersion               | This is not a Looking Glass error, do not report this
[E]   1253393983              main.c:842  | reportBadVersion               | Please install the matching host application for this client
[E]   1253393985              main.c:1151 | lg_run                         | Expected KVMFR version 14, got 19
[E]   1253393987              main.c:1152 | lg_run                         | Client version: B5.0.1
[E]   1253393988              main.c:1154 | lg_run                         |   Host version: B5-347-g719f30ae`

Looking more into this I see that the LG_BUILD_VERSION is hardcoded into lgproxy

`./lgproxy/common/include/version.h:static const char * LG_BUILD_VERSION = "B5-347-g719f30ae";`

**Comment by beanfacts** [comment]
The version string is not hardcoded. It is generated at compile time based on the submodule version checked out in the `repos/` folder.

https://github.com/telescope-proj/lgproxy/blob/main/lgproxy/CMakeLists.txt#L121

To use a different version, modify the highlighted lines in the `.gitmodules` file:

```diff
[submodule "repos/LookingGlass"]
	path = repos/LookingGlass
+	url = https://github.com/telescope-proj/LookingGlass.git
+ 	branch = client-dxtc
```

Then run a resync before recompiling: `git submodule sync --recursive`.

Using release versions is not currently supported due to the old header version, although this is likely to change in B6. We unfortunately have a severe lack of time and funding in order to extend support beyond the current KVMFR version (19).

```
[E] 1253393985 main.c:1151 | lg_run | Expected KVMFR version 14, got 19
```

LGProxy currently has no function to verify the KVMFR version ahead of time, although you will most likely run into errors if you use the wrong version. Verify the Looking Glass KVMFR version in `repos/LookingGlass/common/include/common/KVMFR.h`.

https://github.com/gnif/LookingGlass/blob/master/common/include/common/KVMFR.h#L31

**Comment by efschu** [comment]
hmm

now when I try to compile lg host app from your sources

> git clone https://github.com/telescope-proj/LookingGlass --recursive -b client-dxtc
cd LookingGlass
mkdir host/build
cd host/build
cmake -DCMAKE_TOOLCHAIN_FILE=../toolchain-mingw64.cmake ..
make -j $(nproc)

I get 

> [ 64%] Building C object common/CMakeFiles/lg_common.dir/src/cpuinfo.c.obj
/home/efeu/Downloads/efeu_lg/LookingGlass/repos/libttc/src/etcpak/ProcessRGB.cpp: In function ‘void CompressEtc2Rgba(const uint32_t*, uint64_t*, uint32_t, size_t, bool)’:
/home/efeu/Downloads/efeu_lg/LookingGlass/repos/libttc/src/etcpak/ProcessRGB.cpp:2809:13: error: ‘sel’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
 2809 |     __m128i recVal16 = rangeMul[sel];
      |             ^~~~~~~~
compilation terminated due to -Wfatal-errors.
cc1plus: all warnings being treated as errors
make[2]: *** [ttc/CMakeFiles/ttc.dir/build.make:137: ttc/CMakeFiles/ttc.dir/src/etcpak/ProcessRGB.cpp.obj] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:399: ttc/CMakeFiles/ttc.dir/all] Fehler 2
make[1]: *** Auf noch nicht beendete Prozesse wird gewartet …
[ 66%] Linking C static library liblg_common.a
[ 66%] Built target lg_common
make: *** [Makefile:136: all] Fehler 2

**Comment by beanfacts** [comment]
Hi, I cannot seem to reproduce this issue on my Fedora 36 machine. Could you provide more information about the OS and compiler you are using?

![issue3](https://user-images.githubusercontent.com/43068204/186904226-3b6e980e-3f9e-499c-a6d3-5e85dfaedb7a.png)

This is an issue with the etcpak library which we use for texture compression, so we'll have to roll out a fix ourselves to mitigate these compiler warnings.

In the meantime, as you mentioned you don't need texture compression support, you can use the `master` branch instead of `client-dxtc`. You could also download a matching version from the Looking Glass website, which supports NvFBC, instead of compiling it yourself as well. Please let me know if the master branch works as expected for you.

Thanks

**Comment by efschu** [comment]
So after a long time of use, I checked rdma traffic and realized that when using nvfbc the compression setting is being ignored.

So, good for me, I did not see any difference, because there were no differences, and not because I'm old :)

Is this a bug, or is compression with nvfbc just unsupported?

(compression is working w/o nvfbc, but actual the performance is only "OK" for resolutions up to 1920x1080, but with higher res eg. 2560x1440, performance is to bad for me (40-70 ups and really noticable mouse lag - while I get easily 280 ups and "zero" mouse lag w/o compression - R9 5950X with 2080ti)

**Comment by beanfacts** [comment]
Compression with NVFBC is unsupported due to issues with the NVFBC API's proprietary licenses and our lack of hardware (yes, you can run it on GeForce, but as this was originally an academic project, we had to operate strictly within licensing constraints). The main performance issue is that the CPU is being used for texture compression, but I don't have the expertise to write a GPU-based texture compression shader which would significantly improve compression performance.

At the moment, since the Telescope version of Looking Glass is now woefully out of date, it is expected that the next version of LGProxy will drop compression support for now and use Looking Glass upstream until a more maintainable solution is found. This does mean that it will no longer run on gigabit/2.5G networks, but I think even with compression the performance is not great on such networks anyway.

**Comment by efschu** [comment]
Tnx for the clarification
